# -*- coding: utf-8 -*-
"""heartdisesepred

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGtQ83nnn9G-Hi4_L2BsbHWvM8mwoML-
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("johnsmith88/heart-disease-dataset")

print("Path to dataset files:", path)

import pandas as pd

df = pd.read_csv(path + "/heart.csv")
df.head()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Separate features (X) and target (y)
X = df.drop('target', axis=1)
y = df['target']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize StandardScaler
scaler = StandardScaler()

# Apply scaling to training and testing features
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Data split and scaled successfully!")
print(f"X_train shape: {X_train_scaled.shape}")
print(f"X_test shape: {X_test_scaled.shape}")

from sklearn.linear_model import LogisticRegression

# Initialize and train the Logistic Regression model
model = LogisticRegression(random_state=42)
model.fit(X_train_scaled, y_train)

print("Logistic Regression model trained successfully!")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Make predictions on the scaled test set
y_pred = model.predict(X_test_scaled)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Display confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'], yticklabels=['Actual 0', 'Actual 1'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""### Training a Random Forest Classifier

Now, let's try a different model: a Random Forest Classifier. This ensemble learning method can often provide higher accuracy than logistic regression, especially with complex datasets. We'll train it on the same scaled data and then evaluate its performance.
"""

from sklearn.ensemble import RandomForestClassifier

# Initialize and train the Random Forest Classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_scaled, y_train)

print("Random Forest Classifier trained successfully!")

"""### Random Forest Model Evaluation

Let's evaluate the performance of our Random Forest model and compare it with the Logistic Regression model.
"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Make predictions on the scaled test set using the Random Forest model
y_pred_rf = rf_model.predict(X_test_scaled)

# Calculate accuracy
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Random Forest Accuracy: {accuracy_rf:.4f}")

# Display classification report
print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))

# Display confusion matrix
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
print("\nRandom Forest Confusion Matrix:")
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix_rf, annot=True, fmt='d', cmap='Greens', cbar=False,
            xticklabels=['Predicted 0', 'Predicted 1'], yticklabels=['Actual 0', 'Actual 1'])
plt.title('Random Forest Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

"""### Model Accuracy Comparison

Here's how the two models stack up in terms of accuracy:

*   **Logistic Regression:**  Approximately **79.51%**
*   **Random Forest Classifier:** Approximately **98.54%**

It's clear that the Random Forest model performed significantly better on this dataset.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a dictionary of model accuracies
model_accuracies = {
    'Logistic Regression': accuracy,
    'Random Forest': accuracy_rf
}

# Convert to a pandas Series for easy plotting
accuracy_series = pd.Series(model_accuracies)

plt.figure(figsize=(8, 6))
sns.barplot(x=accuracy_series.index, y=accuracy_series.values, palette='viridis')
plt.title('Model Accuracy Comparison')
plt.xlabel('Model')
plt.ylabel('Accuracy')
plt.ylim(0, 1) # Set y-axis limit from 0 to 1 for accuracy

# Add accuracy values on top of the bars
for index, value in enumerate(accuracy_series.values):
    plt.text(index, value + 0.02, f'{value:.4f}', ha='center', va='bottom')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""### Saving the Model

Now that we've trained and evaluated our models, we can save the best performing one (the Random Forest Classifier) to a pickle file. This allows us to persist the trained model and reload it later for making predictions without needing to retrain it.
"""

import pickle

# Define the filename for the pickle file
filename = 'random_forest_model.pkl'

# Save the Random Forest model to the file
with open(filename, 'wb') as file:
    pickle.dump(rf_model, file)

print(f"Random Forest model saved successfully as '{filename}'")